# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeometricalArea
                                 A QGIS plugin
 Плагин для расчета геометрической площади объектов внутри шейп фйла
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-22
        copyright            : (C) 2021 by Шамсутдинов Р.
        email                : test@test.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeometricalArea class from file GeometricalArea.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geometrical_area import GeometricalArea
    return GeometricalArea(iface)
